### PR TITLE
Added new tests to staking and utils

### PR DESCRIPTION
**Pull request by Shloyem**
Added tests to increase code coverage in: 
- goodAaveStakingV2 initialization 
- goodCompoundStakingV2 get gas cost function
- ProxyFactory1967 deploy minimal function

### CODE REVIEW

**Comment by sirpy** [comment]
@Shloyem resovle the conflict

**Comment by Shloyem** [comment]
> @Shloyem resovle the conflict

@sirpy done*
* the code one, not the global one:)

**Comment by sirpy** [comment]
@Shloyem is this PR still relevant?

**Comment by Shloyem** [comment]
> @Shloyem is this PR still relevant?

Nope, removing it

**Pull request closed without merging**
